[project]
name = "book-agentic-patterns"
version = "0.1.0"
description = "Agentic patterns"
readme = "README.md"
requires-python = ">=3.12.2"
dependencies = [
    "dotenv>=0.9.9",
    "fastmcp>=2.14.2",
    "openai>=2.14.0",
    "pydantic-ai>=1.39.0",
]
